vich_uploader:
    db_driver: orm

    mappings:
        books:
           uri_prefix: /images/books
           upload_destination: '%kernel.project_dir%/public/images/books'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
